### ISSUE TITLE
Issue running with shared credentials assuming a role with MFA set

### ISSUE THREAD

**Issue by egarbi** [rebuy-de/aws-nuke#252]
```
cat ~/.aws/credentials
[test]
aws_access_key_id = XXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
```
cat ~/.aws/config
[profile testing]
mfa_serial = arn:aws:iam::012345678910:mfa/enrique.garbi@example.com
source_profile = test
role_arn = arn:aws:iam::012345678910:role/admin
```
```
regions:
- eu-west-2

account-blacklist:
- "99999999999" # production

resource-types:
  targets:
  - EC2Instance

accounts:
  "012345678910": {} # testing
```
```
./aws-nuke -v --profile testing -c config.yaml
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/rebuy-de/aws-nuke/pkg/awsutil.(*Credentials).Session(0xc4201b4460, 0x3115af8, 0x9, 0xffffffffffffffff, 0xc42019f980, 0x10ce901)
	/go/src/github.com/rebuy-de/aws-nuke/pkg/awsutil/session.go:111 +0x10b
github.com/rebuy-de/aws-nuke/pkg/awsutil.NewAccount(0x7ffeefbffb70, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201615f0, ...)
	/go/src/github.com/rebuy-de/aws-nuke/pkg/awsutil/account.go:20 +0xee
github.com/rebuy-de/aws-nuke/cmd.NewRootCommand.func2(0xc420098d80, 0xc42009af00, 0x0, 0x5, 0x0, 0x0)
	/go/src/github.com/rebuy-de/aws-nuke/cmd/root.go:49 +0xcf
github.com/rebuy-de/aws-nuke/vendor/github.com/spf13/cobra.(*Command).execute(0xc420098d80, 0xc420070070, 0x5, 0x5, 0xc420098d80, 0xc420070070)
	/go/src/github.com/rebuy-de/aws-nuke/vendor/github.com/spf13/cobra/command.go:643 +0x3ef
github.com/rebuy-de/aws-nuke/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420098d80, 0xc4201a06d8, 0xc42009ab90, 0xc42009abe0)
	/go/src/github.com/rebuy-de/aws-nuke/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/rebuy-de/aws-nuke/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420098d80, 0xc4200001a0, 0xc4200001a0)
	/go/src/github.com/rebuy-de/aws-nuke/vendor/github.com/spf13/cobra/command.go:692 +0x2b
main.main()
	/go/src/github.com/rebuy-de/aws-nuke/main.go:21 +0x2f
```

**Comment by svenwltr** [comment]
@egarbi Not sure how this ever worked. Yet, I cannot reproduce this. For some reason your setup causes *aws-nuke* to create multiple sessions in the same region. Apparently this is not an usual case, since the code is laying there for a while.

Gets fixed in #253.

**Comment by egarbi** [comment]
@svenwltr thanks, could be related to cross-account setting?? 
In my setup, I'm using a user in an account assuming roles in a different one.

**Comment by svenwltr** [comment]
The cross-account setting shouldn't be a problem, since we are using this, too. But the MFA might be a problem.

We just created a [new release](https://github.com/rebuy-de/aws-nuke/releases/tag/v2.5.0) with the bugfix. Please reopen if the problem still occurs.

**Comment by egarbi** [comment]
@svenwltr  Now Im getting this error:
```
Error: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

**Comment by egarbi** [comment]
but the way it would be useful, and actually enough for me, if you allow environment variables to be set with temporal tokens.
In that way, we can use `aws-vault` for example of similar tools to pre-set the variables before running.
Something like:
```
aws-vault exec admin-lab -- ./aws-nuke -v -c config.yaml
```

**Comment by FernandoMiguel** [comment]
Many of us use aws-vault without issues
Are you sure you don't have a left over credencials file?

**Comment by FernandoMiguel** [comment]
BTW, have you tried --server ?

**Comment by svenwltr** [comment]
I think the issue isn't aws-vault, but requiring MFA for it. The reason for this error is a missing parameter in the session creation. I already fixed it, but *aws-nuke* is currently creating a lot of sessions, which means it want a new MFA token every time. Therefore I have to reduce amount of required the session creations now.

**Comment by svenwltr** [comment]
It is merged now. We will do a new release beginning of next week, after some tests.
