### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by rowanu** [rebuy-de/aws-nuke#280]
Got this error:

````
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/rebuy-de/aws-nuke/resources.(*CloudFormationStack).Remove(0xc0032fd1a0, 0x3167a01, 0x7)
        /Users/rowan/go/src/github.com/rebuy-de/aws-nuke/resources/cloudformation-stack.go:52 +0x467
github.com/rebuy-de/aws-nuke/cmd.(*Nuke).HandleRemove(0xc000524000, 0xc003365b30)
        /Users/rowan/go/src/github.com/rebuy-de/aws-nuke/cmd/nuke.go:247 +0x37
github.com/rebuy-de/aws-nuke/cmd.(*Nuke).HandleQueue(0xc000524000)
        /Users/rowan/go/src/github.com/rebuy-de/aws-nuke/cmd/nuke.go:226 +0x197
github.com/rebuy-de/aws-nuke/cmd.(*Nuke).Run(0xc000524000, 0xb, 0xc00017c070)
        /Users/rowan/go/src/github.com/rebuy-de/aws-nuke/cmd/nuke.go:90 +0x5d5
github.com/rebuy-de/aws-nuke/cmd.NewRootCommand.func2(0xc00017ec80, 0xc000096820, 0x0, 0x5, 0x0, 0x0)
        /Users/rowan/go/src/github.com/rebuy-de/aws-nuke/cmd/root.go:62 +0x2da
github.com/spf13/cobra.(*Command).execute(0xc00017ec80, 0xc00001e1f0, 0x5, 0x5, 0xc00017ec80, 0xc00001e1f0)
        /Users/rowan/go/src/github.com/spf13/cobra/command.go:753 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0xc00017ec80, 0xc000024ef8, 0xc000096780, 0xc0000967d0)
        /Users/rowan/go/src/github.com/spf13/cobra/command.go:843 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc00017ec80, 0xc00019ff88, 0xc000078058)
        /Users/rowan/go/src/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
        /Users/rowan/go/src/github.com/rebuy-de/aws-nuke/main.go:23 +0x27
````

I'm guessing it's just because I have a silly number of resources?

Not sure if this is worth fixing, feel free to close if not.

**Comment by rowanu** [comment]
Thanks for pushing a fix so quickly. I had about ~120 CFN stacks, but I think I only got the error after a few retries - Many of the stacks failed to delete due to buckets having data, etc. so there were a lot of them stuck in `DELETE_FAILED` state.

Unfortunately I won't be able to test it in anger for a little while; My colleagues don't want "surprise nukes" for some reason... 🤷‍♂️ I plan to try again next month, so I'll close for now and will post back if needed.

**Comment by rowanu** [comment]
Sorry for all the comments, I didn't realise GitHub was struggling...

**Comment by svenwltr** [comment]
Ok. Please reopen this, if you notice it is still not working correctly.
